### PR TITLE
Create Hoshi||星⚔️

### PR DESCRIPTION
**Pull request by YoruTsuki228**

### CODE REVIEW

**Comment by FadliDarmawan** [comment]
What?

**Comment by Ftwrr** [comment]
?

**Comment by jauhari21** [comment]
> _No description provided._

Fitur apa nih

**Comment by KazukoGans** [comment]
?

**Comment by ariffb25** [comment]
nani koreng?

**Comment by FadliDarmawan** [comment]
> nani koreng?

Kentang goreng

**Comment by RC047** [comment]
Respect+

**Comment by Nurutomo** [comment]
Leave a comment

**Pull request closed without merging**
