### PR TITLE
[ Feature ] SetBotName , SetBotBio

### PR DESCRIPTION
**Pull request by NurFy**

### CODE REVIEW

**Comment by Ftwrr** [comment]
hmmmm

**Comment by NurFy** [comment]
> hmmmm

(●__●)

**Comment by TOXIC-DEVIL** [comment]
> hmmmm

#520 💔

**Comment by TOXIC-DEVIL** [comment]
> > hmmmm
> 
> (●__●)

This Pull Will Accepted, After some days or months only 😖 Because Check my pull #520 its still not merged so think when will your pull merge 😂😂

**Comment by NurFy** [comment]
> > > hmmmm
> > 
> > 
> > (●__●)
> 
> This Pull Will Accepted, After some days or months only 😖 Because Check my pull #520 its still not merged so think when will your pull merge 😂😂

TERUS AING KUDU KUMAHA?

**Comment by TOXIC-DEVIL** [comment]
> > > > hmmmm
> > > 
> > > 
> > > (●__●)
> > 
> > 
> > This Pull Will Accepted, After some days or months only 😖 Because Check my pull #520 its still not merged so think when will your pull merge 😂😂
> 
> TERUS AING KUDU KUMAHA?

Wait For The Merge That's It 🙂

**Pull request merged**
