### PR TITLE
Owner Irul ganteng sendiri

### PR DESCRIPTION
**Pull request by Zairulkhaq**
apt update && apt upgrade
apt install git -y
apt install nodejs -y
apt install ffmpeg -y
apt install imagemagick -y
git clone https://github.com/Nurutomo/wabot-aq
cd wabot-aq
npm install
npm update
npm start

### CODE REVIEW

**Comment by Zairulkhaq** [comment]
apt update && apt upgrade
apt install git -y
apt install nodejs -y
apt install ffmpeg -y
apt install imagemagick -y
git clone https://github.com/Nurutomo/wabot-aq
cd wabot-aq
npm install
npm update

**Comment by Zairulkhaq** [comment]
apt update && apt upgrade
apt install git -y
apt install nodejs -y
apt install ffmpeg -y
apt install imagemagick -y
git clone https://github.com/Nurutomo/wabot-aq
cd wabot-aq
npm install
npm update
npm start

**Comment by Zairulkhaq** [comment]
Irulbotz

**Comment by Zairulkhaq** [comment]
### 081334690126

**Comment by Zairulkhaq** [comment]
https://youtube.com/channel/UCaLeY6D60suD-2blIgBgHIA jangan lupa subscribe ya

**Comment by Zairulkhaq** [comment]
https://youtube.com/channel/UCaLeY6D60suD-2blIgBgHIA

**Comment by unx21** [comment]
Semangat gan 🔥🔥

**Pull request closed without merging**
