### PR TITLE
siapa disini yang cita citanya gatau

### PR DESCRIPTION
**Pull request by Ftwrr**

### CODE REVIEW

**Comment by RC047** [comment]
Bjir :v

**Comment by jauhari21** [comment]
> _No description provided._

Bro scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
Jadi kek gimana?

**Comment by Ftwrr** [comment]
> > _No description provided._
> 
> Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> Jadi kek gimana?

donglot satu satu

**Comment by jauhari21** [comment]
> > > _No description provided._
> > 
> > 
> > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > Jadi kek gimana?
> 
> donglot satu satu

Habis itu?

**Comment by Ftwrr** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > Jadi kek gimana?
> > 
> > 
> > donglot satu satu
> 
> Habis itu?



> > > > _No description provided._
> > > 
> > > 
> > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > Jadi kek gimana?
> > 
> > 
> > donglot satu satu
> 
> Habis itu?

`let handler = async (m, { conn }) => {
let konto ='./src/cewe.mp3'
conn.sendFile(m.chat, konto, 'cewe.mp3', null, m, true, {
  type: 'audioMessage', // paksa tanpa convert di ffmpeg
  ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
})
}
handler.customPrefix = /^(cewe)$/i
handler.command = new RegExp
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null
handler.exp = 100

module.exports = handler`

**Comment by KazukoGans** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > Jadi kek gimana?
> > > 
> > > 
> > > donglot satu satu
> > 
> > 
> > Habis itu?
> 
> > > > > _No description provided._
> > > > 
> > > > 
> > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > Jadi kek gimana?
> > > 
> > > 
> > > donglot satu satu
> > 
> > 
> > Habis itu?
> 
> `let handler = async (m, { conn }) => {
> let konto ='./src/cewe.mp3'
> conn.sendFile(m.chat, konto, 'cewe.mp3', null, m, true, {
> type: 'audioMessage', // paksa tanpa convert di ffmpeg
> ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
> })
> }
> handler.customPrefix = /^(cewe)$/i
> handler.command = new RegExp
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.exp = 100
> 
> module.exports = handler`

G work

**Comment by jauhari21** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > Jadi kek gimana?
> > > 
> > > 
> > > donglot satu satu
> > 
> > 
> > Habis itu?
> 
> > > > > _No description provided._
> > > > 
> > > > 
> > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > Jadi kek gimana?
> > > 
> > > 
> > > donglot satu satu
> > 
> > 
> > Habis itu?
> 
> `let handler = async (m, { conn }) => {
> let konto ='./src/cewe.mp3'
> conn.sendFile(m.chat, konto, 'cewe.mp3', null, m, true, {
> type: 'audioMessage', // paksa tanpa convert di ffmpeg
> ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
> })
> }
> handler.customPrefix = /^(cewe)$/i
> handler.command = new RegExp
> handler.owner = false
> handler.mods = false
> handler.premium = false
> handler.group = false
> handler.private = false
> 
> handler.admin = false
> handler.botAdmin = false
> 
> handler.fail = null
> handler.exp = 100
> 
> module.exports = handler`

Work thanks hehe

**Comment by KazukoGans** [comment]
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > > Jadi kek gimana?
> > > > 
> > > > 
> > > > donglot satu satu
> > > 
> > > 
> > > Habis itu?
> > 
> > 
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > > Jadi kek gimana?
> > > > 
> > > > 
> > > > donglot satu satu
> > > 
> > > 
> > > Habis itu?
> > 
> > 
> > `let handler = async (m, { conn }) => {
> > let konto ='./src/cewe.mp3'
> > conn.sendFile(m.chat, konto, 'cewe.mp3', null, m, true, {
> > type: 'audioMessage', // paksa tanpa convert di ffmpeg
> > ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v
> > })
> > }
> > handler.customPrefix = /^(cewe)$/i
> > handler.command = new RegExp
> > handler.owner = false
> > handler.mods = false
> > handler.premium = false
> > handler.group = false
> > handler.private = false
> > handler.admin = false
> > handler.botAdmin = false
> > handler.fail = null
> > handler.exp = 100
> > module.exports = handler`
> 
> Work thanks hehe

G work oi

**Comment by jauhari21** [comment]
> > > > > > > _No description provided._
> > > > > > 
> > > > > > 
> > > > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > > > Jadi kek gimana?
> > > > > 
> > > > > 
> > > > > donglot satu satu
> > > > 
> > > > 
> > > > Habis itu?
> > > 
> > > 
> > > > > > > _No description provided._
> > > > > > 
> > > > > > 
> > > > > > Bro bagi scriptnya kalo pake audio yg ini https://github.com/AlvioAdjiJanuar/SuaraCewek
> > > > > > Jadi kek gimana?
> > > > > 
> > > > > 
> > > > > donglot satu satu
> > > > 
> > > > 
> > > > Habis itu?
> > > 
> > > 
> > > `let handler = async (m, { conn }) => { let konto ='./src/cewe.mp3' conn.sendFile(m.chat, konto, 'cewe.mp3', null, m, true, { type: 'audioMessage', // paksa tanpa convert di ffmpeg ptt: true // true diatas ga work, sebab dipaksa tanpa convert ;v }) } handler.customPrefix = /^(cewe)$/i handler.command = new RegExp handler.owner = false handler.mods = false handler.premium = false handler.group = false handler.private = false handler.admin = false handler.botAdmin = false handler.fail = null handler.exp = 100 module.exports = handler`
> > 
> > 
> > Work thanks hehe
> 
> G work oi

Lah gua work, lu salah kali. Audionya taro di src

**Comment by Nurutomo** [comment]
pake await aja dah, kenapa pake then ;v

padahal itu async

**Comment by Ftwrr** [comment]
> pake await aja dah, kenapa pake then ;v
> 
> padahal itu async

gatau aku bang, aku cuman asal copy paste :')

**Comment by RC047** [comment]
> > pake await aja dah, kenapa pake then ;v
> > padahal itu async
> 
> gatau aku bang, aku cuman asal copy paste :')

Bot kyk Farhan beda buat nurutomo

**Pull request merged**
