### PR TITLE
Simi Simi Updated ✅️

### PR DESCRIPTION
**Pull request by toxic-devil**
Changed Response : simi simi 🙂
Kindly accept atleast this on 😔

### CODE REVIEW

**Comment by Ftwrr** [comment]
no significant difference :/

**Comment by TOXIC-DEVIL** [comment]
> no significant difference :/

No difference but the text changed 🙂

**Comment by Ftwrr** [comment]
> > no significant difference :/
> 
> No difference but the text changed 🙂

then

**Comment by FadliDarmawan** [comment]
> > > no significant difference :/
> > 
> > No difference but the text changed 🙂
> 
> then

Kinda cool detail, sometimes...
But yes, no significant difference

**Comment by FadliDarmawan** [comment]
Thx @TOXIC-DEVIL maybe i can add to my bot

Yeah some ppl think if the bot is humanity

**Comment by TOXIC-DEVIL** [comment]
> Thx @TOXIC-DEVIL maybe i can add to my bot
> 
> Yeah some ppl think if the bot is humanity

😂 💕

**Pull request closed without merging**
