### PR TITLE
No Api

### PR DESCRIPTION
**Pull request by qisyana**

### CODE REVIEW

**Comment by Ftwrr** [comment]
Cannot read properties of undefined (reading 'user')

**Comment by qisyana** [comment]
> Cannot read properties of undefined (reading 'user')

Lupa di pasang ini

    "axios": "^0.23.0",
Di package.json 🙏

**Comment by Ftwrr** [comment]
> > Cannot read properties of undefined (reading 'user')
> 
> Lupa di pasang ini
> 
> ```
> "axios": "^0.23.0",
> ```
> 
> Di package.json 🙏

versi axiosnya harus 0.23.0 kah? soalnya ini gw pake 0.24.0

**Comment by qisyana** [comment]
IMG-20211104-WA0002

**Comment by qisyana** [comment]
> > > Cannot read properties of undefined (reading 'user')
> > 
> > 
> > Lupa di pasang ini
> > ```
> > "axios": "^0.23.0",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Di package.json pray
> 
> versi axiosnya harus 0.23.0 kah? soalnya ini gw pake 0.24.0

Aku bisa

**Comment by Ftwrr** [comment]
uhh okey

**Pull request closed without merging**
