### PR TITLE
pinteretetetetette

### PR DESCRIPTION
**Pull request by Ftwrr**
:(

### CODE REVIEW

**Comment by Ftwrr** [comment]
kok kalian bisa nge merge, gw ngga :)

**Comment by BochilGaming** [comment]
> kok kalian bisa nge merge, gw ngga :)

Wkwkwk

**Comment by ariffb25** [comment]
cek email trs acc undangan kolabolatornya

**Comment by Ftwrr** [comment]
> cek email trs acc undangan kolabolatornya

thangs ingfo

**Comment by anshuljai** [comment]
> > cek email trs acc undangan kolabolatornya
> 
> thangs ingfo

give your wa nomor to ariffb

**Comment by Ftwrr** [comment]
> > > cek email trs acc undangan kolabolatornya
> > 
> > 
> > thangs ingfo
> 
> give your wa nomor to ariffb

my wa nomor buat apa?

**Comment by ariffb25** [comment]
https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G ga masuk juga no prob sih, it's up to u

**Comment by Ftwrr** [comment]
> https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G ga masuk juga no prob sih, it's up to u

udah masuk

**Pull request merged**
