### PR TITLE
The most awaited plugins :)

### PR DESCRIPTION
**Pull request by anshuljai**
Works on all groups (no split error :v )

### CODE REVIEW

**Comment by anshuljai** [comment]
@Nurutomo  please remove my bot name if you merge :'v.....i forgot  :')

**Comment by Ftwrr** [comment]
pake node-fetch aja :v

**Comment by anshuljai** [comment]
> pake node-fetch aja :v

no +_+

**Comment by Nurutomo** [comment]
nope :v

**Comment by anshuljai** [comment]
-_-

**Comment by Ftwrr** [comment]
#176  :v

**Comment by anshuljai** [comment]
> #176 :v

but that have split error...mine does not have 😕

**Pull request closed without merging**
