### PR TITLE
update sticker

### PR DESCRIPTION
**Pull request by Ftwrr**

### CODE REVIEW

**Comment by Ftwrr** [comment]
ya gitu

**Comment by qisyana** [comment]
Cannot find module 'wa-sticker-formatter'
Bagian npm i wa-sticker-formatter

**Comment by Ftwrr** [comment]
> > ya gitu
> 
> Screenshot_2021-11-03-23-08-46-302_com termux

coba ``npm i github:alensaito1/wa-sticker-formatter``

**Comment by Ftwrr** [comment]
ehh, keknya emang ga support termux

**Comment by qisyana** [comment]
Ohh ga support termux

**Comment by unx21** [comment]
> ehh, keknya emang ga support termux

emang gak di support bang

**Comment by Ftwrr** [comment]
> > ehh, keknya emang ga support termux
> 
> emang gak di support bang

owhh okee

**Pull request closed without merging**
