### PR TITLE
All canvas feature of random api :D 

### PR DESCRIPTION
**Pull request by anshuljai**
@Nurutomo you can remove trigger.js if you want :')

### CODE REVIEW

**Comment by Nurutomo** [comment]
delete trigger.js :p
if you add the `effects` list

**Comment by anshuljai** [comment]
ok :)

**Comment by anshuljai** [comment]
@Nurutomo  done ;)

**Comment by Nurutomo** [comment]
:|
that was too much

**Comment by anshuljai** [comment]
so i am closing this one -_

**Pull request closed without merging**
