### PR TITLE
Search Anime With Image

### PR DESCRIPTION
**Pull request by Nobuyaki**
Screenshot_2021-04-18-18-10-13

### CODE REVIEW

**Comment by Kokoronationz** [comment]
Ijin ambil code nya

**Comment by janganlahkau** [comment]
Keren cuk:v

**Comment by Miaweers** [comment]
Akaowkw akhirnya :v

**Comment by jauhari21** [comment]
> Screenshot_2021-04-19-07-59-33-88
> Ini kenapa ya gan?
`<ref *1> BaileysError: given message C7B9BAD8FE59C0F2CA2CC363DE82901A is not a media message
    at WAConnection.updateMediaMessage (/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:278:19)
    at /data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
    at WAConnection.descriptor.value (/data/data/com.termux/files/home/wabot-aq/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:22:15)
    at WAConnection.downloadM (/data/data/com.termux/files/home/wabot-aq/lib/simple.js:312:65)
    at WebMessageInfo.m.download (/data/data/com.termux/files/home/wabot-aq/lib/simple.js:419:44)
    at WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/plugins/wait.js:13:21)
    at WAConnection.handler (/data/data/com.termux/files/home/wabot-aq/handler.js:181:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 0,
  context: WebMessageInfo {
    messageStubParameters: [],
    labels: [],
    key: MessageKey {
      remoteJid: '6283877698966-1559214920@g.us',
      fromMe: false,
      id: 'C7B9BAD8FE59C0F2CA2CC363DE82901A'
    },
    message: Message { ephemeralMessage: [FutureProofMessage] },
    messageTimestamp: Long { low: 1618794766, high: 0, unsigned: true },
    status: 0,
    participant: '6283877698966@s.whatsapp.net',
    ephemeralOutOfSync: false,
    epoch: 1001,
    id: 'C7B9BAD8FE59C0F2CA2CC363DE82901A',
    isBaileys: false,
    chat: '6283877698966-1559214920@g.us',
    fromMe: false,
    isGroup: true,
    sender: '6283877698966@s.whatsapp.net',
    mtype: 'imageMessage',
    msg: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [Array],
      url: 'https://mmg.whatsapp.net/d/f/AlxjC_3tSwDbia2txEUwzZhTHpe8_3p8fUbEwy_D9aA4.enc',
      mimetype: 'image/jpeg',
      caption: '#wait',
      fileSha256: <Buffer 46 66 48 eb 1a 0b 12 66 af 5a 9a cc 0c 59 72 40 f6 23 77 a7 3d e9 da 29 85 23 f3 ee 02 ab 6a f8>,
      fileLength: [Long],
      height: 720,
      width: 1280,
      mediaKey: <Buffer 25 b6 21 31 81 59 0b c3 19 2f cc 08 a2 28 d6 54 9c ab af 56 12 c4 bf 14 37 64 16 17 53 3c c1 69>,
      fileEncSha256: <Buffer 80 be 9f 0a 75 6e a6 42 d8 35 4b de 56 25 3b 51 f8 08 e3 d4 20 a8 53 0d fb 7d 79 2a b7 4a f3 6c>,
      directPath: '/v/t62.7118-24/30779013_2885038998404778_7501090796476959048_n.enc?ccb=11-4&oh=9be78f8a6362d0637b7309330f07bf3a&oe=60A2FDA9',
      mediaKeyTimestamp: [Long],
      jpegThumbnail: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 1b 1b 1b 1b 1c 1b 1e 21 21 1e 2a 2d 28 2d 2a 3d 38 33 33 38 3d 5d 42 47 42 ... 623 more bytes>,
      contextInfo: [ContextInfo],
      scansSidecar: <Buffer 48 d4 de 52 d6 2e 1a 2d d4 90 9a 52 40 16 bc c3 e5 57 4c c6 4f ea 9c c5 04 fd 29 e2 78 ca 54 ff f7 1e 0a b4 c4 03 71 6d>,
      midQualityFileSha256: <Buffer bb cc 24 22 f5 aa b6 a8 44 18 17 4c 96 d7 0d f2 bb 23 ee 7e 80 bd 7f 46 e8 75 68 18 fc 4b 96 dc>
    },
    quoted: null,
    mentionedJid: [],
    download: [Function (anonymous)],
    text: '#wait',
    reply: [Function (anonymous)],
    copy: [Function (anonymous)],
    forward: [Function (anonymous)],
    copyNForward: [Function (anonymous)],
    cMod: [Function (anonymous)],
    exp: 21,
    limit: false,
    plugin: 'wait.js',
    isCommand: true,
    error: [Circular *1]
  }
}`

**Comment by Nobuyaki** [comment]
> Screenshot_2021-04-19-07-59-33-88
> Ini kenapa ya gan?

Ada Yg Kau Rubah Gak Codenya?

**Comment by jauhari21** [comment]
> > Screenshot_2021-04-19-07-59-33-88
> > Ini kenapa ya gan?
> 
> Ada Yg Kau Rubah Gak Codenya?

Ga ada, cuma nambahin handler.limit = true biar kena limit hehe. Ngaruh ya?

**Comment by jauhari21** [comment]
Oh iya anehnya cuma di grup itu doang yg ga bisa, di grub lain bisa" aja.

**Comment by Kokoronationz** [comment]
> Oh iya anehnya cuma di grup itu doang yg ga bisa, di grub lain bisa" aja.

Disappearing Message bikin error

**Comment by Kokoronationz** [comment]
Screenshot_20210419_144311
Screenshot_20210419_145119

**Comment by jauhari21** [comment]
> > Oh iya anehnya cuma di grup itu doang yg ga bisa, di grub lain bisa" aja.
> 
> Disappearing Message bikin error

Oh pesan sementara bikin eror ya gan?

**Comment by jauhari21** [comment]
> > Oh iya anehnya cuma di grup itu doang yg ga bisa, di grub lain bisa" aja.
> 
> Disappearing Message bikin error

Oke gan dah bisa terima kasih infonya

**Pull request merged**
