### PR TITLE
Adding Install Instructions In Ubuntu-Termux

### PR DESCRIPTION
**Pull request by TheUnknownPeople-user**
The command ( ubuntu ) is the ubuntu login command
If it's not there, type this :

[ echo "proot-distro login ubuntu-20.04" > $PREFIX/bin/ubuntu ]

### CODE REVIEW

**Comment by iniariaaa** [comment]
Nah gini kan enak:v

**Comment by TheUnknownPeople-user** [comment]
> Nah gini kan enak:v

👍

**Comment by ariffb25** [comment]
ok

**Comment by TheUnknownPeople-user** [comment]
> ok

thanks

**Comment by Adiixyz** [comment]
when i use `apt` : E: Unable to locate package proot-distro

when i use `pkg` : it is installed

**Comment by TheUnknownPeople-user** [comment]
> when i use `apt` : E: Unable to locate package proot-distro
> 
> when i use `pkg` : it is installed

What's your Termux version? If it's below 117, it's appropriate because the Apt Full Command can work on 117 

If you haven't installed the new one, you can install it here:

https://f-droid.org/repo/com.termux_117.apk

**Pull request merged**
