### PR TITLE
update add premium

### PR DESCRIPTION
**Pull request by ariffb25**

### CODE REVIEW

**Comment by anshuljai** [comment]
you forgot to add databse prem = true....

you only added if the user is already premium 😁

**Comment by ariffb25** [comment]
what's wrong?

**Comment by anshuljai** [comment]
> what's wrong?

you only added....if the person is already premium......you not added to make a person premium through bot

**Comment by ariffb25** [comment]
did you try it? 🤔

**Comment by ariffb25** [comment]
image
image
image

works as it should, you should try it first before commenting

**Comment by Nurutomo** [comment]
meski sementara, tapi gpp

**Pull request merged**
