### PR TITLE
New Command - Leavegc ✅️

### PR DESCRIPTION
**Pull request by toxic-devil**
Hey!! @Nurutomo

New Command Leavegc ✅️

### CODE REVIEW

**Comment by Ftwrr** [comment]
:v

**Comment by TOXIC-DEVIL** [comment]
> :v

😳

**Comment by TOXIC-DEVIL** [comment]
> :v

May I Contact You? Let me know your Instagram Name? 💬

**Comment by FadliDarmawan** [comment]
> Hey!! @Nurutomo
> 
> New Command Leavegc ✅️

@Nurutomo doesnt online again....

**Comment by TOXIC-DEVIL** [comment]
> > Hey!! @Nurutomo
> > New Command Leavegc ✅️
> 
> @Nurutomo doesnt online again....

Why? 😳

**Comment by TOXIC-DEVIL** [comment]
> > Hey!! @Nurutomo
> > New Command Leavegc ✅️
> 
> @Nurutomo doesnt online again....

Who Will Merge these PR 🙂

**Comment by TOXIC-DEVIL-ABHINAV** [comment]
> > > Hey!! @Nurutomo
> > > New Command Leavegc ✅️
> > 
> > 
> > @Nurutomo doesnt online again....
> 
> Who Will Merge these PR 🙂

@anshuljai

**Comment by ariffb25** [comment]
add this: 
1. exit all groups
2. exit group based on group id and validation

**Comment by TOXIC-DEVIL** [comment]
> add this:
> 
> 1. exit all groups
> 2. exit group based on group id and validation

Sure, I will try. But now merge this one ✅️

**Comment by TOXIC-DEVIL** [comment]
> add this:
> 
> 1. exit all groups
> 2. exit group based on group id and validation

2. I didn't understand few more explanation needed!😂

**Comment by BochilGaming** [comment]
> add this:
> 
> 1. exit all groups
> 2. exit group based on group id and validation



> add this:
> 
> 1. exit all groups
> 2. exit group based on group id and validation

gini  kah? #533

**Pull request closed without merging**
