### PR TITLE
Create pinterest.js

### PR DESCRIPTION
**Pull request by anshuljai**
@Nurutomo  addedimage tags

### CODE REVIEW

**Comment by RC047** [comment]
Please don't copy code from github.com/RC047/Kuhong-V4 :/

**Comment by anshuljai** [comment]
> Please don't copy code from github.com/RC047/Kuhong-V4 for pull request,, thats wrong :/

there is not a plugin....as mine in your repo....i coded that from random api...so stop taking credits 😏

**Comment by RC047** [comment]
> > Please don't copy code from github.com/RC047/Kuhong-V4 for pull request,, thats wrong :/
> 
> there is not a plugin....as mine in your repo....i coded that from random api...so stop taking credits 😏 and fyi you use base64....i use simple and fast responsive method 😎

Just the same stupid lie

**Comment by RC047** [comment]
want to be a contributor but not capital

**Comment by RC047** [comment]
F

**Comment by jauhari21** [comment]
Ngasih request fitur seakan akan dia yg buat skript, padahal skript ini itu masih nanya ke gua tadi wkwkwk. Hamdeh, paling engga hargai yg bikin lah

**Comment by RC047** [comment]
> Ngasih request fitur seakan akan dia yg buat skript, padahal skript ini itu masih nanya ke gua tadi wkwkwk. Hamdeh, paling engga hargai yg bikin lah

Dia copy script w

**Review by Nurutomo — CHANGES_REQUESTED** [review]
use encodeURIComponent please

**Comment by jauhari21** [comment]
> > Ngasih request fitur seakan akan dia yg buat skript, padahal skript ini itu masih nanya ke gua tadi wkwkwk. Hamdeh, paling engga hargai yg bikin lah
> 
> Dia copy script w

Iya tau kok :v, kan gua nyindir dia

**Comment by Nurutomo** [comment]
> use encodeURIComponent please

**Pull request closed without merging**
