### PR TITLE
New Command - Short ✅️ 

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
New Command - Short ✅️
Shortene Your Long Links 🔄

Merge This One @ariffb25

### CODE REVIEW

**Comment by ariffb25** [comment]
preferably using the API from xteam.xyz

**Comment by TOXIC-DEVIL** [comment]
> preferably using the API from xteam.xyz

Okay Now?! 🔄

**Comment by ariffb25** [comment]
have you tried and the results are correct?

**Comment by TOXIC-DEVIL** [comment]
> have you tried and the results are correct?

Yes ✅️

**Comment by TOXIC-DEVIL** [comment]
> have you tried and the results are correct?

Now Merge 😘 Its 100% correct

**Comment by ariffb25** [comment]
image
check again :/ why are there 2 fetch

**Comment by TOXIC-DEVIL** [comment]
> image
> check again :/ why are there 2 fetch

Oh Sorry! There is 2 fetch 😂 I only notice now 🙂

**Comment by TOXIC-DEVIL** [comment]
> image
> check again :/ why are there 2 fetch

Fixed 👋 Try Again ✅️

**Comment by ariffb25** [comment]
you better try first, check again

**Comment by TOXIC-DEVIL** [comment]
> you better try first, check again

Oh 🙂 I can't! Because my phone isn't available now! It got died. And This is my another one 💔 no space in this. I will buy another. But not now, So I can't check 😔

**Comment by BochilGaming** [comment]
> image
> check again :/ why are there 2 fetch

Eh btw itu group membernya brp terus, boleh minta link :v

**Comment by ariffb25** [comment]
@BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G

**Comment by Kerala-Boy** [comment]
> @BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G

Just check and merge plz 🙂

**Comment by ariffb25** [comment]
> > @BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G
> 
> Just check and merge his plz, [ He is my friend ] 🙂

fix it first, before someone else makes a new PR

**Comment by TOXIC-DEVIL** [comment]
> > > @BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G
> > 
> > 
> > Just check and merge his plz, [ He is my friend ] 🙂
> 
> fix it first, before someone else makes a new PR

Fixed na? 😔

**Comment by TOXIC-DEVIL** [comment]
> > > @BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G
> > 
> > 
> > Just check and merge his plz, [ He is my friend ] 🙂
> 
> fix it first, before someone else makes a new PR

A game coming soon @ariffb25 😂

**Comment by BochilGaming** [comment]
> @BochilGaming https://chat.whatsapp.com/GVwpKf83s42D1CnIfDW19G

Makasihh..

**Pull request closed without merging**
