### PR TITLE
Added new Command -- ✅️

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
Kick all ✅️

### CODE REVIEW

**Comment by Ftwrr** [comment]
rawan banned ga sih? :/

**Comment by syahrularranger** [comment]
> rawan banned ga sih? :/

Iya auto diban sama mark :v

**Comment by TOXIC-DEVIL** [comment]
> rawan banned ga sih? :/

Oh Why Did You Said Like That? 😔

**Comment by TOXIC-DEVIL** [comment]
> > rawan banned ga sih? :/
> 
> Iya auto diban sama mark :v

What Mark? What auto?
:(
:(
:(

**Comment by TOXIC-DEVIL** [comment]
Sorry, I will not contribute any more :(

**Comment by Ftwrr** [comment]
njirr sad boi

**Comment by TOXIC-DEVIL** [comment]
> njirr sad boi

You Said that I will get ban? From Where   :(     For What   :(   It Makes me sad  :(:(:(:(:(:(:(:(:():):):):):):):)

**Comment by Ftwrr** [comment]
> > njirr sad boi
> 
> You Said that I will get ban? From Where :( For What :( It Makes me sad :(:(:(:(:(:(:(:(:():):):):):):):)

jika kita menggunakan perintah kickall nomor kita akan di banned :v

**Comment by TOXIC-DEVIL** [comment]
> > > njirr sad boi
> > 
> > 
> > You Said that I will get ban? From Where :( For What :( It Makes me sad :(:(:(:(:(:(:(:(:():):):):):):):)
> 
> jika kita menggunakan perintah kickall nomor kita akan di banned :v

Oh that 😂

**Pull request closed without merging**
