### PR TITLE
session.data.json

### PR DESCRIPTION
**Pull request by JulianKastara09**

### CODE REVIEW

**Comment by unx21** [comment]
Nice 👍

**Comment by Lord-Patrick** [comment]
Mangtap

**Comment by MuhammadRestu999** [comment]
Mantap :trollface:

**Comment by qisyana** [comment]
Mantap 😂

**Comment by ilmanhdyt** [comment]
Hayoloh

**Comment by Nurhidayat2619** [comment]
Wah sesi gratis nih mayan buat dihack awowkwkwk

**Pull request closed without merging**
