### PR TITLE
Fixed NPM Error ❗️ Important Pull ✅️

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
Fixed NPM ✅️
@Ftwrr @ariffb25

IMG_20210802_214607
IMG_20210802_214549

### CODE REVIEW

**Comment by TOXIC-DEVIL** [comment]
**Both Can Be Used [ npm i or npm update or bash install.sh ] So Updated Readme Back.**

**Review by Ftwrr — COMMENTED** [review]
lah emangnya bisa langsung npm update yahh?

**Review by Ftwrr — COMMENTED** [review]
njirr ini kenapa dihapus

**Comment by Ftwrr** [comment]
gw malah jadi eror : closed connection, reason replaced

**Comment by BochilGaming** [comment]
> gw malah jadi eror : closed connection, reason replaced

kasih conn.version = [2, 2123, 8]. Terus banyak fitur yang error gara gara downgrade kayak, jadibot, join, dll

**Comment by TOXIC-DEVIL** [comment]
> is it possible to directly npm update?

Yes ✅️

**Comment by TOXIC-DEVIL** [comment]
> why did this shit get deleted

Accidently

**Comment by TOXIC-DEVIL** [comment]
> > I got an error instead : closed connection, reason replaced
> 
> love conn.version = [2, 2123, 8]. Then there are many features that error because of downgrades like, bot, join, etc

That's right but this is temporary 💬

**Pull request closed without merging**
